### ISSUE TITLE
Event delegation

### ISSUE THREAD

**Issue by jonnitto** [Websilk/Selector#4]
Event delegation doesn't work:

```
$(document).on('click', '.hello-world', function(event) {
    event.preventDefault();
   // Actions
});
```

**Comment by markentingh** [comment]
Ah yes, I'll be working on event deligation soon. Thank you for bringing this up, jonnitto.

**Comment by markentingh** [comment]
I just pushed my changes which includes deferred events. There's definitely a lot more I need to do in order to get this framework up to par with jQuery. If you see anything else that needs work, let me know. Thanks again!

**Comment by markentingh** [comment]
I just pushed my changes which includes deferred events. There's definitely a lot more I need to do in order to get this framework up to par with jQuery. If you see anything else that needs work, let me know. Thanks again!

**Comment by jonnitto** [comment]
Hey cool, thanks! There's still an issue: If you have an tag inside another, the delegation doesn't get fired. Other tools like [Cash](https://github.com/kenwheeler/cash) or [Gator](https://github.com/ccampbell/gator) can handle it smoothly:

I made a small demo of the issue:
https://codepen.io/jonnitto/pen/a3b1a85e2c32708dbf23e84d2dddcbfd/?editors=1011

**Comment by markentingh** [comment]
Cash looks amazing! The code structure is beautiful, too. I think I'm going to fork that project instead of working on this one. I started this project so I could learn advanced javascript techniques, but I think cash is much more elegant. Thank you for sharing this with me.
